###

POST http://localhost:3000/recipe/upload
Content-Type: application/json

{
  "category": "soup",
    "name": "recipeName",
    "instructions": "hdhhdwdbwe fwefwe fweufwe fwefvwef w e",
    "preparationTime": 10,
    "dishes": 10,
    "ingredients": [ "milk", "eggs" ]

}



###